config/routes.rb
Rails.application.routes.draw do
  resources :pimos
  
  devise_for :users
  resources :projects do 
      resources :donates
  end
  get 'pages/about'

  get 'pages/contact'

  get 'entrepreneur' => "projects#entrepreneur"

  root 'projects#index'

end

app/models/donate.rb
class Donate < ActiveRecord::Base
	validates :address, :city, :state, presence: true

	belongs_to :project
	belongs_to :donor, class_name: "User"
	belongs_to :entrepreneur,class_name: "User"
end

app/controllers/donates_controller.rb
class DonatesController < ApplicationController
  before_action :set_donate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /donates
  # GET /donates.json
  def index
    @donates = Donate.all
  end

  # GET /donates/1
  # GET /donates/1.json
  def show
  end

  # GET /donates/new
  def new
    @donate = Donate.new
    @project = Project.find(params[:project_id])
  end

  # GET /donates/1/edit
  def edit
  end

  # POST /donates
  # POST /donates.json
  def create
    @donate = Donate.new(donate_params)
    @project = Project.find(params[:project_id])
    @donate.donor_id = current_user.id

    respond_to do |format|
      if @donate.save
        format.html { redirect_to @donate, notice: 'Donate was successfully created.' }
        format.json { render :show, status: :created, location: @donate }
      else
        format.html { render :new }
        format.json { render json: @donate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donates/1
  # PATCH/PUT /donates/1.json
  def update
    respond_to do |format|
      if @donate.update(donate_params)
        format.html { redirect_to @donate, notice: 'Donate was successfully updated.' }
        format.json { render :show, status: :ok, location: @donate }
      else
        format.html { render :edit }
        format.json { render json: @donate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donates/1
  # DELETE /donates/1.json
  def destroy
    @donate.destroy
    respond_to do |format|
      format.html { redirect_to donates_url, notice: 'Donate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donate
      @donate = Donate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donate_params
      params.require(:donate).permit(:address, :city, :state)
    end
end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/views/donates/_form.html.erb
<%= form_for([@project, @donate]) do |f| %>
  <% if @donate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donate.errors.count, "error") %> prohibited this donate from being saved:</h2>

      <ul>
      <% @donate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donates/edit.html.erb
<h1>Editing Donate</h1>

<%= render 'form' %>

<%= link_to 'Show', @donate %> |
<%= link_to 'Back', donates_path %>

app/views/donates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Donates</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donates.each do |donate| %>
      <tr>
        <td><%= donate.address %></td>
        <td><%= donate.city %></td>
        <td><%= donate.state %></td>
        <td><%= link_to 'Show', donate %></td>
        <td><%= link_to 'Edit', edit_donate_path(donate) %></td>
        <td><%= link_to 'Destroy', donate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donate', new_donate_path %>

app/views/donates/new.html.erb
<h1>New Donate</h1>

<%= render 'form' %>

<%= link_to 'Back', project_donates_path %>

app/views/donates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @donate.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @donate.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @donate.state %>
</p>

<%= link_to 'Edit', edit_donate_path(@donate) %> |
<%= link_to 'Back', donates_path %>