config/routes.rb
Rails.application.routes.draw do
  resources :pimos
  
  devise_for :users
  resources :projects do 
      resources :donates
  end
  get 'pages/about'

  get 'pages/contact'

  get 'entrepreneur' => "projects#entrepreneur"

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	 has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :region, :country, :organization_name, :leader_name, :organization_type, :address, :organization_id, :description, :impact_people ,
  :technical_assistance, :amount, :raised, presence:true
  validates :amount, numericality: { greater_than: 0 }
  validates_attachment_presence :image

  belongs_to :user
  has_many :donates
  belongs_to :pimo
end




 

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:entrepreneur, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

   # GET /entrepreneur
  def entrepreneur
     @projects = Project.where(user: current_user).order("created_at DESC")    
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order("created_at DESC")
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:region, :country, :project_type, :organization_name, :leader_name, :organization_type, :address, :organization_id, :description, :impact_people, :technical_assistance, :raised, :amount, :image)
    end

    def check_user
      if current_user != @project.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, :html => { :multipart => true }) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="form-group">
    <%= f.label :region, 'Geographical Region' %><br>
    <%= f.text_field :region, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :country, 'Project Country'%><br>
    <%= f.text_field :country , class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :project_type, 'Project technical area' %><br>
    <%= f.text_field :project_type , class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :organization_name, 'Name of your organization'%><br>
    <%= f.text_field :organization_name , class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :leader_name, 'Name of key leaders'%><br>
    <%= f.text_field :leader_name , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :organization_type, 'Type of organization ' %><br>
    <%= f.text_field :organization_type , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address, 'Address/localization of the organization in country' %><br>
    <%= f.text_field :address , class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :organization_id, 'Organization’s local official identification number'%><br>
    <%= f.text_field :organization_id , class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :description, 'Explain issues/problems that proposed project aims to address and solutions proposed'%><br>
    <%= f.text_area :description , class: "form-control"  %>
  </div>
 <div class="form-group">
    <%= f.label :impact_people, 'Provide an estimate of the number of direct and indirect beneficiaries of the project and how their lives are positively affected by the project activities' %><br>
    <%= f.text_area :impact_people , class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :technical_assistance, 'Specific technical assistance' %><br>
    <%= f.text_area :technical_assistance , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :amount, 'Total amount needed in US$'%><br>
    <%= f.text_field :amount , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :raised, 'Total amount raised in US$'%><br>
    <%= f.text_field :raised , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image , class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.submit class: "btn btn-warning" %>
  </div>
<% end %>

app/views/projects/_sidebar.html.erb
<div class="fb-like-box" data-href="http://www.facebook.com/pages/Global-Self-Help/514619285239445" data-width="252" data-show-faces="true" data-stream="false" data-header="false">
</div>

<div class="list-group">
  <a href="#" class="list-group-item active">
    Cras justo odio
  </a>
  <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
  <a href="#" class="list-group-item">Morbi leo risus</a>
  <a href="#" class="list-group-item">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item">Vestibulum at eros</a>
</div>

<div class="list-group">
  <a href="#" class="list-group-item active">
    Cras justo odio
  </a>
  <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
  <a href="#" class="list-group-item">Morbi leo risus</a>
  <a href="#" class="list-group-item">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item">Vestibulum at eros</a>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<div class="row">
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
  <div class="col-md-4">
  <%= render 'sidebar' %>
  </div>
</div>




<%= link_to 'Show', @project, class: "btn btn-link" %> |
<%= link_to 'Back', projects_path , class: "btn btn-link" %>

app/views/projects/entrepreneur.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Project</th>
    <th class="center">Goal</th>
    <th class="center">Raised</th>
    <th class="center">Action</th>
  </tr>
      <% @projects.each do |project| %>
    <tr>
      <td> <%= image_tag project.image.url(:thumb)%></td>
      <td><%= project.project_type %></td>
      <td><%= number_to_currency(project.amount)%></td>
      <td><%= number_to_currency(project.raised) %></td>
       <td> 
        <div class="btn-group">
           <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
           </button>
          <ul class="dropdown-menu" role="menu">
            <li> <%= link_to "View", project, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_project_path(project), class: "btn btn-link" %></li>
          <!--  <li><%= link_to 'Destroy', project, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li> -->
          </ul>
        </div>        
       </td>
    </tr>
    <% end %>
</table>

 

app/views/projects/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Global Self-Help </h1>
    <h2>Improving people's live</h2>
</div>
 <div class="container">  
<div class="center">
 <%= link_to "Create Your Project", new_project_path, class: "btn btn-success btn-lg "%>
   
 </div>
 <div class="row">
    <% @projects.each do |project| %>
       <div class="col-md-3 ">
         <div class="thumbnail ">
            <%= image_tag project.image.url %>
            <div class="caption">
                <h4> <b><%= project.project_type %></h4></b>
                <p> <%= project.region %>, <%= project.country %></p>
                <p><%= project.impact_people %></p>   

                <table class="table table-condensed">
                    <tr>
                      <td>Goal</td>
                      <td>Raised</td>
                    </tr>
                    <tr>
                      <td class="danger" ><%= "#{number_to_currency(project.amount)}"%></td>
                      <td class="success"><%= "#{number_to_currency(project.raised)}"%></td> 
                    </tr>
              </table>            
                  
             <%= link_to 'Show detail', project , class: "btn btn-link" %> 
              <% if (user_signed_in?) && (current_user == project.user) %>
                <%= link_to 'Edit', edit_project_path(project) , class: "btn btn-link" %> 
                <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-link" %>
             <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<div class="row">
  <div class="col-md-8">
  	<%= render 'form' %>
  </div>
  <div class="col-md-4">
  	 <%= render 'sidebar' %>
  </div>
</div>


<%= link_to 'Back', projects_path, class: "btn btn-link" %>

app/views/projects/show.html.erb
<div class="container-fluid">
  <div class="row">
      <div class="col-md-6">
          <div class="thumbnail">
            <%= image_tag @project.image.url %>        
          </div>
           <div>
             <ul>
                <li id="menu_documents"><a href="#">Documents</a></li>
                <li id="menu_forum" class="selected"><a href="#" class="selected">Forum</a></li>
                <li id="menu_events"><a href="#">Events</a></li>
              </ul>

          </div>   
    </div>
    <div class="col-md-6">
      <h3 class="content"> <%= @project.project_type %></h3>
        <table class="table">
          <tr class="danger">
            <td>Amount needed</td>
            <td><%= number_to_currency(@project.amount) %></td> 
          </tr>
          <tr class="warning">
            <td>Region</td>
            <td><%= @project.region %></td> 
          </tr>
          <tr class="warning">
            <td>Country</td>
            <td><%= @project.country %></td> 
          </tr>
           <tr class="warning">
            <td>Organization name</td>
            <td><%= @project.organization_name %></td> 
          </tr>
          <tr class="warning">
            <td>Organization type</td>
            <td><%= @project.organization_type %> </td> 
          </tr>
           <tr class="warning">
            <td>Leader name</td>
            <td><%= @project.leader_name %></td> 
          </tr>
           <tr class="warning">
            <td>Project description</td>
            <td><%= @project.description %></td> 
          </tr>
           <tr class="warning">
            <td>Impact people</td>
            <td><%= @project.impact_people %></td> 
          </tr>
           <tr class="warning">
            <td>Technical assistance</td>
            <td><%= @project.technical_assistance %></td> 
          </tr>
           <tr class="success">
            <td>Amound raised</td>
            <td><%= number_to_currency(@project.raised) %></td> 
          </tr>
        </table>
        <div class="center">
            <%= link_to " Donate Now ", projects_path, class: "btn btn-warning btn-lg"%>
          </div>   
     </div>
  </div>
</div>
<div class="container">
<% if current_user == @project.user  %>
  <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', projects_path, class: "btn btn-link" %>
</div>