config/routes.rb
Rails.application.routes.draw do
  resources :pimos
  
  devise_for :users
  resources :projects do 
      resources :donates
  end
  get 'pages/about'

  get 'pages/contact'

  get 'entrepreneur' => "projects#entrepreneur"

  root 'projects#index'

end

app/models/pimo.rb
class Pimo < ActiveRecord::Base
	validates :area, presence:true

	 belongs_to :user
     has_many :projects
end

app/controllers/pimos_controller.rb
class PimosController < ApplicationController
  before_action :set_pimo, only: [:show, :edit, :update, :destroy]

  # GET /pimos
  # GET /pimos.json
  def index
    @pimos = Pimo.all
  end

  # GET /pimos/1
  # GET /pimos/1.json
  def show
  end

  # GET /pimos/new
  def new
    @pimo = Pimo.new
  end

  # GET /pimos/1/edit
  def edit
  end

  # POST /pimos
  # POST /pimos.json
  def create
    @pimo = Pimo.new(pimo_params)

    respond_to do |format|
      if @pimo.save
        format.html { redirect_to @pimo, notice: 'Pimo was successfully created.' }
        format.json { render :show, status: :created, location: @pimo }
      else
        format.html { render :new }
        format.json { render json: @pimo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pimos/1
  # PATCH/PUT /pimos/1.json
  def update
    respond_to do |format|
      if @pimo.update(pimo_params)
        format.html { redirect_to @pimo, notice: 'Pimo was successfully updated.' }
        format.json { render :show, status: :ok, location: @pimo }
      else
        format.html { render :edit }
        format.json { render json: @pimo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pimos/1
  # DELETE /pimos/1.json
  def destroy
    @pimo.destroy
    respond_to do |format|
      format.html { redirect_to pimos_url, notice: 'Pimo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pimo
      @pimo = Pimo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pimo_params
      params.require(:pimo).permit(:area)
    end
end

app/helpers/pimos_helper.rb
module PimosHelper
end

app/views/pimos/_form.html.erb
<%= form_for(@pimo) do |f| %>
  <% if @pimo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pimo.errors.count, "error") %> prohibited this pimo from being saved:</h2>

      <ul>
      <% @pimo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pimos/edit.html.erb
<h1>Editing Pimo</h1>

<%= render 'form' %>

<%= link_to 'Show', @pimo %> |
<%= link_to 'Back', pimos_path %>

app/views/pimos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pimos</h1>

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pimos.each do |pimo| %>
      <tr>
        <td><%= pimo.area %></td>
        <td><%= link_to 'Show', pimo %></td>
        <td><%= link_to 'Edit', edit_pimo_path(pimo) %></td>
        <td><%= link_to 'Destroy', pimo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pimo', new_pimo_path %>

app/views/pimos/new.html.erb
<h1>New Pimo</h1>

<%= render 'form' %>

<%= link_to 'Back', pimos_path %>

app/views/pimos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @pimo.area %>
</p>

<%= link_to 'Edit', edit_pimo_path(@pimo) %> |
<%= link_to 'Back', pimos_path %>