config/routes.rb
Rails.application.routes.draw do
  resources :pimos
  
  devise_for :users
  resources :projects do 
      resources :donates
  end
  get 'pages/about'

  get 'pages/contact'

  get 'entrepreneur' => "projects#entrepreneur"

  root 'projects#index'

end

app/views/layouts/_footer.html.erb
<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">                
                 <div class="col-md-4">
                    <h3> About US </h3>
                    <ul>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h3> Contact Us </h3>
                    <address>
			   	  <strong>Global Self-Help Inc. </strong><br>
				  5672 Bridgecross Drive, <br>
				 Sacramento CA, 95835 US<br>
				  <abbr title="Phone">Phone:</abbr> 1(916)-234-3959<br>
				  <abbr title="Email">Email:</abbr> <a>info@globalselfhelp.org</a>
				</address>
                </div>
               
                <div class="col-md-4">
                    <h3> Follow Us</h3>
                    <ul class="social">
                        <li> <a target="_blank" href="https://www.facebook.com/pages/Global-Self-Help/514619285239445?fref=ts"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-youtube">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row--> 
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->
    
    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © 2015 Global Self-Help . All right reserved. </p>
            <div class="pull-right">
                <ul class="nav nav-pills payments">
                	<li><i class="fa fa-cc-visa"></i></li>
                    <li><i class="fa fa-cc-mastercard"></i></li>
                    <li><i class="fa fa-cc-amex"></i></li>
                    <li><i class="fa fa-cc-paypal"></i></li>
                </ul> 
            </div>
        </div>
    </div>
    <!--/.footer-bottom--> 
</footer>

<!--
<div class="container">
	<hr>
	  	<div class="row">
		    <div class="col-md-4">
		    	<h4>About Us</h4><br>
		    </div>
		    <div class="col-md-4">
		    	<h4>Follow us</h4><br>    
		    </div>
		    <div class="col-md-4">
			    <address>
			    <h4>Contact Us</h4>
				  <strong>Global Self-Help Inc. </strong><br>
				  5672 Bridgecross Drive, <br>
				 Sacramento CA, 95835 US<br>
				  <abbr title="Phone">Phone:</abbr> 1(916)-234-3959<br>
				  <abbr title="Email">Email:</abbr> info@globalselfhelp.org
				</address>
		    </div>
		  </div>
	  </div>
<div class="container">  
	<p>Copyright © 2015 Global Self-Help | All Rights Reserved</p> 
</div>
-->

app/views/layouts/_header.html.erb
 <div class="container">  
  <div class="row">
    <div class="col-md-4"><%= link_to(image_tag("logo.png", :alt => "logo", :title => "Home"), "/") %></div>
    <div class="col-md-4"></div>    
    <div class="col-md-4"></div>    
  </div>
</div>
  <nav class="navbar navbar-default" role="navigation">
  <div class="container"> 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <a class="navbar-brand" href="/">Home</a></li>
        <li><%= link_to "About",  pages_about_path %></li> 
        <li><%= link_to "Contact",  pages_contact_path %></li>         
     </ul>
     <ul class="nav navbar-nav navbar-right">
     <% if user_signed_in? %>
        <li><%= link_to "Manage Projects",   entrepreneur_path %></li> 
        <li><%= link_to "Edit Profile",   edit_user_registration_path %></li>  
        <li><%= link_to "Sign Out",  destroy_user_session_path, method: :delete %></li>  
      <% else %>           
       <li><%= link_to "Log In",   new_user_session_path %></li>  
       <li><%= link_to "Sign Up",  new_user_registration_path %></li>  
      <% end %> 
      </ul>
    </div>
  </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Global Self-Help</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "success" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
  
<%= yield %>

</div>
<%= render 'layouts/footer' %>
</body>
</html>